@startuml
|Casa D|
start
:Carta en\nla puerta de casa;
note left: 4143 -> Sillas
|Casa E|
:Papiroflexia de las sillas;
note right: 4224 -> Lata café
|Casa D|
:Acertijo de las edades;
note left: 2097 -> Kallax
|Casa E|
:Acertijo de las letras en inglés;
note left: 2416 -> Tele
|Casa D|
:Fotos en la tele;
note right: 2413 -> cubo pelotas
|Patio|
:globos de hielo;
note right: 7856 -> escaleras
|Casa E|
:acertijo en escaleras;
note right: 3271 -> lámpara
|Casa D|
:números en la lámpara;
note right: 5078 -> garaje
:cajetín de las llaves;
note right: mensaje secreto
:árbol de navidad;
note right: Llaves del coche
|Garaje|
:REGALOS;
stop
@enduml
